version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    commit-message:
      prefix: "dependabot"
    groups:
      development-dependencies:
        exclude-patterns:
        - "@kkszb*"
      minor-changes:
        update-types:
        - "minor"
        - "patch"
