name: "Coverage badges"

permissions:
    contents: write

on:
    push
jobs:
    cov_badge:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              
            - uses: wouterds/github-coverage-badge-action@v1.0.1
              with:
                  coverage-summary-path: coverage-summary.json
