name: "Coverage badges"

permissions:
    contents: write

jobs:
    cov_badge:
        runs-on: ubuntu-latest
        steps:
            - uses: wouterds/github-coverage-badge-action@v1.0.1
              with:
                  coverage-summary-path: coverage-summary.json
